# Generated by Django 5.2.8 on 2025-12-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monstro',
            name='dados_completos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='monstro',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='monstro',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
